### ISSUE TITLE
Research Open Badges

### ISSUE THREAD

**Issue by MichaelViaene** [oSoc18/gentlestudent#3]

**Comment by MichaelViaene** [comment]
@mrvdries

**Comment by MichaelViaene** [comment]
@MarieSophie4

**Comment by jeborsel** [comment]
Since you are planning to use Badgr : SurfNet in The Netherlands is working on a fork of Badgr , the project is called Edubadges. They also did a code audit (of their own code and of badgr code) , maybe interesting to have a look at that as well, you can find it here: https://github.com/edubadges/audit

**Comment by jeborsel** [comment]
just fyi , the best api to use, will be that of Badgr , Edubadges is just in a pilot phase

**Comment by mrvdries** [comment]
Open badges dev page: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html
